livros = ['Mateus',
    'Marcos',
    'Lucas',
    'João',
    'Atos dos Apóstolos',
    'Romanos',
    '1Coríntios',
    '2Coríntios',
    'Gálatas',
    'Efésios',
    'Filipenses',
    'Colossenses',
    '1Tessalonicenses',
    '2Tessalonicenses',
    '1Timóteo',
    '2Timóteo',
    'Tito',
    'Filémon',
    '1Pedro',
    '2Pedro',
    '1João',
    '2João',
    '3João',
    'Hebreus',
    'Tiago',
    'Judas',
    'Apocalipse'];

    console.log ("O novo testamento possui" + livros.length +"livros");
